name: "RepoB Action"
description: "Intermediate action interacting with RepoC"

runs:
  using: "composite"
  steps:
    - name: Use RepoC Action
      uses: 0xhellhound/repoC@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Dummy Step
      run: echo "RepoB: You've been pwned!"
