name: "RepoB Action"
description: "Intermediate action incorporating RepoC dynamically"

inputs:
  token:
    description: "GitHub Token for accessing RepoC"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use RepoC Action
      uses: 0xhellhound/repoC@main
      with:
        token: ${{ inputs.token }}

    - name: Dummy Step
      run: echo "RepoB: Dummy step completed!"
      shell: bash
