name: "RepoB Action"
description: "Intermediate action interacting with RepoC"

inputs:
  token:
    description: "GitHub Token for accessing RepoC"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use RepoC Action
      uses: 0xhellhound/repoC@main
      with:
        token: ${{ inputs.token }}

    - name: Dummy Step
      env:
        HOLLY_SECRET: ${{ secrets.HOLLY_SECRET }}
      run: |
        echo "Dummy step running..."
        echo "HOLLY_SECRET: $HOLLY_SECRET"
      shell: bash
